apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.12.0
        volumeMounts:
        - name: host-logs
          mountPath: /host/var/log
        - name: config
          mountPath: /usr/share/logstash/pipeline/
      volumes:
      - name: host-logs
        hostPath:
          path: /var/log
      - name: config
        configMap:
          name: logstash-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk
data:
  logstash.conf: |
    input {
      file {
        path => "/host/var/log/**/*.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
      }
    }
    filter {
      # Filtros podem ser adicionados aqui conforme necessário
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch.elk.svc.cluster.local:9200"]
        user => "elastic"
        password => "mereHISTE"
        index => "logs-%{+YYYY.MM.dd}"
      }
    }