services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  init:
    build: .
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow_user:airflow_pass@postgres/airflow_db
      AIRFLOW__CORE__FERNET_KEY: 'mQ6AcQTF8yf8HIIfjDwB4laLb2V3UGbADGbS0eMxjCI='
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com
      "

  webserver:
    build: .
    restart: always
    depends_on:
      - init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow_user:airflow_pass@postgres/airflow_db
      AIRFLOW__CORE__FERNET_KEY: 'mQ6AcQTF8yf8HIIfjDwB4laLb2V3UGbADGbS0eMxjCI='
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./dbt:/opt/airflow/dbt
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    build: .
    restart: always
    depends_on:
      - webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow_user:airflow_pass@postgres/airflow_db
      AIRFLOW__CORE__FERNET_KEY: 'mQ6AcQTF8yf8HIIfjDwB4laLb2V3UGbADGbS0eMxjCI='
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./dbt:/opt/airflow/dbt
    command: scheduler

volumes:
  postgres-db-volume:
