apiVersion: v1
kind: ServiceAccount
metadata:
  name: kibana
  namespace: elk
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kibana-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kibana-role-binding
subjects:
- kind: ServiceAccount
  name: kibana
  namespace: elk
roleRef:
  kind: ClusterRole
  name: kibana-role
  apiGroup: rbac.authorization.k8s.io