apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  labels:
    component: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: Alocador
    node.name: Master
    path.data: /usr/share/elasticsearch/data
    http:
      host: 0.0.0.0
      port: 9200
    bootstrap.memory_lock: true
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.license.self_generated.type: basic
    # Enable xpack.security which is provided in basic subscription
    xpack.security.enabled: true